# Generated by Django 3.1.4 on 2020-12-16 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_title', models.CharField(blank=True, max_length=255, null=True)),
                ('written_body', models.TextField(blank=True, null=True)),
                ('voice_body', models.FileField(blank=True, null=True, upload_to='')),
                ('voice_text', models.TextField(blank=True, null=True)),
                ('location_tags', models.CharField(blank=True, max_length=255, null=True)),
                ('text_tags', models.TextField(blank=True, null=True)),
                ('file_upload', models.FileField(blank=True, null=True, upload_to='')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('privacy', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
