# Generated by Django 3.1.4 on 2020-12-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_title', models.CharField(blank=True, max_length=255, null=True)),
                ('written_body', models.TextField(blank=True, null=True)),
                ('voice_body_temp', models.CharField(blank=True, max_length=255, null=True)),
                ('voice_text', models.TextField(blank=True, null=True)),
                ('medium', models.CharField(max_length=7)),
                ('location_tags', models.CharField(blank=True, max_length=255, null=True)),
                ('text_tags', models.TextField(blank=True, null=True)),
                ('published_date', models.CharField(blank=True, max_length=255, null=True)),
                ('privacy', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['published_date'],
            },
        ),
    ]
