# Generated by Django 3.1.4 on 2020-12-17 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='file_upload',
            field=models.TextField(blank=True, null=True),
        ),
    ]
